# Generated by Django 5.1.1 on 2024-09-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('precipitation', models.FloatField()),
            ],
            options={
                'db_table': 'weather_data',
                'constraints': [models.UniqueConstraint(fields=('state', 'year', 'date'), name='datewise state weather constraint')],
            },
        ),
    ]
