# Generated by Django 5.1.1 on 2024-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weatherdata',
            name='datewise state weather constraint',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='station',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='weatherdata',
            constraint=models.UniqueConstraint(fields=('station', 'date'), name='datewise station weather constraint'),
        ),
    ]
