# Generated by Django 5.1.1 on 2024-09-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_remove_weatherdata_datewise_station_weather_constraint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('avg_max_temp', models.FloatField()),
                ('avg_min_temp', models.FloatField()),
                ('avg_precipitation', models.FloatField()),
            ],
            options={
                'db_table': 'weather_stats',
                'constraints': [models.UniqueConstraint(fields=('state', 'station', 'year'), name='yearwise stationwise statewise weather constraint')],
            },
        ),
    ]
